/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alan_zjut_hellothreads_MainActivity */

#ifndef _Included_alan_zjut_hellothreads_MainActivity
#define _Included_alan_zjut_hellothreads_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alan_zjut_hellothreads_MainActivity
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_hellothreads_MainActivity_posixThreads
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alan_zjut_hellothreads_MainActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alan_zjut_hellothreads_MainActivity_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     alan_zjut_hellothreads_MainActivity
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alan_zjut_hellothreads_MainActivity_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     alan_zjut_hellothreads_MainActivity
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_hellothreads_MainActivity_nativeWorker
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
