/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alan_zjut_echosocket_EchoClientActivity */

#ifndef _Included_alan_zjut_echosocket_EchoClientActivity
#define _Included_alan_zjut_echosocket_EchoClientActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alan_zjut_echosocket_EchoClientActivity
 * Method:    nativeStartTcpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_echosocket_EchoClientActivity_nativeStartTcpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
