/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alan_zjut_echosocket_LocalSocketActivity */

#ifndef _Included_alan_zjut_echosocket_LocalSocketActivity
#define _Included_alan_zjut_echosocket_LocalSocketActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alan_zjut_echosocket_LocalSocketActivity
 * Method:    nativeStartLocalServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_echosocket_LocalSocketActivity_nativeStartLocalServer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
