/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alan_zjut_echosocket_EchoServerActivity */

#ifndef _Included_alan_zjut_echosocket_EchoServerActivity
#define _Included_alan_zjut_echosocket_EchoServerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alan_zjut_echosocket_EchoServerActivity
 * Method:    nativeStartTcpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_echosocket_EchoServerActivity_nativeStartTcpServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     alan_zjut_echosocket_EchoServerActivity
 * Method:    nativeStartUdpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_echosocket_EchoServerActivity_nativeStartUdpServer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
