/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alan_zjut_aviplayer_BitmapPlayerActivity */

#ifndef _Included_alan_zjut_aviplayer_BitmapPlayerActivity
#define _Included_alan_zjut_aviplayer_BitmapPlayerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alan_zjut_aviplayer_BitmapPlayerActivity
 * Method:    render
 * Signature: (JLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_alan_zjut_aviplayer_BitmapPlayerActivity_render
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
