/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alan_zjut_aviplayer_NativeWindowActivity */

#ifndef _Included_alan_zjut_aviplayer_NativeWindowActivity
#define _Included_alan_zjut_aviplayer_NativeWindowActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alan_zjut_aviplayer_NativeWindowActivity
 * Method:    init
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_aviplayer_NativeWindowActivity_init
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     alan_zjut_aviplayer_NativeWindowActivity
 * Method:    render
 * Signature: (JLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_alan_zjut_aviplayer_NativeWindowActivity_render
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
