/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alan_zjut_aviplayer_OpenGLPlayerActivity */

#ifndef _Included_alan_zjut_aviplayer_OpenGLPlayerActivity
#define _Included_alan_zjut_aviplayer_OpenGLPlayerActivity
#include <GLES/gl.h>
#include <GLES/glext.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alan_zjut_aviplayer_OpenGLPlayerActivity
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_alan_zjut_aviplayer_OpenGLPlayerActivity_init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     alan_zjut_aviplayer_OpenGLPlayerActivity
 * Method:    initSurface
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_aviplayer_OpenGLPlayerActivity_initSurface
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     alan_zjut_aviplayer_OpenGLPlayerActivity
 * Method:    render
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_alan_zjut_aviplayer_OpenGLPlayerActivity_render
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     alan_zjut_aviplayer_OpenGLPlayerActivity
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alan_zjut_aviplayer_OpenGLPlayerActivity_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
